//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleService.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AIVISEntities : DbContext
    {
        public AIVISEntities()
            : base("name=AIVISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chrom_Intervention_Type> Chrom_Intervention_Type { get; set; }
        public virtual DbSet<Chrom_Sequence_Instrument> Chrom_Sequence_Instrument { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Users_Credentials> Users_Credentials { get; set; }
        public virtual DbSet<Chrom_Sequence> Chrom_Sequence { get; set; }
        public virtual DbSet<SiteClient> SiteClients { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<Chrom_Sequence_Trails> Chrom_Sequence_Trails { get; set; }
        public virtual DbSet<Chrom_DataVault> Chrom_DataVault { get; set; }
        public virtual DbSet<Chrom_Server> Chrom_Server { get; set; }
    }
}
