//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chrom_Server
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chrom_Server()
        {
            this.Chrom_DataVault = new HashSet<Chrom_DataVault>();
        }
    
        public int Id { get; set; }
        public string ServerName { get; set; }
        public string ServerUri { get; set; }
        public int ImportedBy { get; set; }
        public System.DateTime ImportedOn { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chrom_DataVault> Chrom_DataVault { get; set; }
        public virtual User User { get; set; }
    }
}
