//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chrom_ProcessingMethod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chrom_ProcessingMethod()
        {
            this.MasterSequences = new HashSet<MasterSequence>();
        }
    
        public int Id { get; set; }
        public int SiteId { get; set; }
        public int DataVaultId { get; set; }
        public System.Guid Chromeleon_Id { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public int AddedBy { get; set; }
        public System.DateTime AddedOn { get; set; }
    
        public virtual Chrom_DataVault Chrom_DataVault { get; set; }
        public virtual Site Site { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterSequence> MasterSequences { get; set; }
    }
}
