//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chrom_Sequence_Instrument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chrom_Sequence_Instrument()
        {
            this.Chrom_Sequence_Trails = new HashSet<Chrom_Sequence_Trails>();
        }
    
        public long Id { get; set; }
        public int SequenceId { get; set; }
        public byte[] Instrument { get; set; }
        public int ImportedBy { get; set; }
        public System.DateTime ImportedOn { get; set; }
    
        public virtual User User { get; set; }
        public virtual Chrom_Sequence Chrom_Sequence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chrom_Sequence_Trails> Chrom_Sequence_Trails { get; set; }
    }
}
