//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chrom_Sequence_Trails
    {
        public long Id { get; set; }
        public int SequenceId { get; set; }
        public Nullable<long> InstrumentId { get; set; }
        public Nullable<int> InterventionTypeId { get; set; }
        public string InjectionName { get; set; }
        public string ProductName { get; set; }
        public string BatchNo { get; set; }
        public string TestName { get; set; }
        public string ARNo { get; set; }
        public Nullable<int> Chrom_Trail_Number { get; set; }
        public Nullable<System.Guid> Chrom_Trail_Id { get; set; }
        public string Trails { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<int> ImportedBy { get; set; }
        public Nullable<System.DateTime> ImportedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> ModifiedOn { get; set; }
        public bool ResolveStatus { get; set; }
        public Nullable<int> ResolveBy { get; set; }
        public string ResolvedRemarks { get; set; }
        public string QMSNumber { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DeletedRemarks { get; set; }
    
        public virtual Chrom_Intervention_Type Chrom_Intervention_Type { get; set; }
        public virtual Chrom_Sequence Chrom_Sequence { get; set; }
        public virtual Chrom_Sequence_Instrument Chrom_Sequence_Instrument { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
