//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chrom_Intervention_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chrom_Intervention_Type()
        {
            this.Chrom_Sequence_Trails = new HashSet<Chrom_Sequence_Trails>();
        }
    
        public int Id { get; set; }
        public string Intervention { get; set; }
        public string InterventionDescription { get; set; }
        public bool IsCritical { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string ChartColorCode { get; set; }
        public string DisplayName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chrom_Sequence_Trails> Chrom_Sequence_Trails { get; set; }
    }
}
