//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterSequence_Injections
    {
        public int Id { get; set; }
        public int MasterSequenceId { get; set; }
        public string InjectionName { get; set; }
        public int InjectionCount { get; set; }
        public string Description { get; set; }
    
        public virtual MasterSequence MasterSequence { get; set; }
    }
}
