//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterSequence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterSequence()
        {
            this.MasterSequence_Injections = new HashSet<MasterSequence_Injections>();
        }
    
        public int Id { get; set; }
        public int SiteId { get; set; }
        public string Name { get; set; }
        public string SampleType { get; set; }
        public string Description { get; set; }
        public Nullable<int> InstrumentMethodId { get; set; }
        public Nullable<int> ProcessingMethodID { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public int AddedBy { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterSequence_Injections> MasterSequence_Injections { get; set; }
        public virtual Site Site { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Chrom_InstrumentMethod Chrom_InstrumentMethod { get; set; }
        public virtual Chrom_ProcessingMethod Chrom_ProcessingMethod { get; set; }
    }
}
