//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sequence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sequence()
        {
            this.Sequence_Details = new HashSet<Sequence_Details>();
        }
    
        public long Id { get; set; }
        public string SequenceName { get; set; }
        public string BatchNo { get; set; }
        public string ARNo { get; set; }
        public string TestName { get; set; }
        public int NoOfTest { get; set; }
        public string ProductCode { get; set; }
        public int ProcessingStatus { get; set; }
        public int AddedBy { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sequence_Details> Sequence_Details { get; set; }
        public virtual Sequence_Status Sequence_Status { get; set; }
        public virtual User User { get; set; }
    }
}
