//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sequence_Details
    {
        public long Id { get; set; }
        public long SequenceId { get; set; }
        public Nullable<decimal> Weight_Sample { get; set; }
        public Nullable<decimal> Avg_Sample { get; set; }
        public string Label_Claim { get; set; }
        public string Stage { get; set; }
        public string Pack { get; set; }
        public string Condition { get; set; }
        public string TimeInterval_Dissolution { get; set; }
        public string SampleWithdraw_Dissolution { get; set; }
        public string TotalVolume_Dissolution { get; set; }
    
        public virtual Sequence Sequence { get; set; }
    }
}
