//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AivisService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Sites
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int SiteId { get; set; }
        public bool IsDafault { get; set; }
    
        public virtual Site Site { get; set; }
        public virtual User User { get; set; }
    }
}
